module Chin2

//let chin2 =
//    let dict = Dictionary<uint16,Specification list>()
//    // 　
//    dict.[41377us] <- [
//    ]
//    // 、
//    dict.[41378us] <- [
//        PenUp
//        Displacement(17y,24y)
//        PenDown
//        Displacement(8y,-5y)
//        Displacement(6y,-8y)
//        Displacement(3y,-8y)
//        PenUp
//        Displacement(-30y,26y)
//        PenDown
//        Displacement(11y,0y)
//        Displacement(6y,-1y)
//        Displacement(10y,-5y)
//        Displacement(4y,-3y)
//        Displacement(2y,-5y)
//        Displacement(1y,-6y)
//        Displacement(-2y,-5y)
//        Displacement(-4y,-2y)
//        Displacement(-5y,1y)
//        Displacement(-3y,3y)
//        Displacement(-5y,10y)
//        Displacement(-7y,6y)
//        Displacement(-9y,4y)
//        Displacement(-1y,2y)
//        Displacement(2y,1y)
//    ]
//    // 。
//    dict.[41379us] <- [
//        PenUp
//        Displacement(18y,2y)
//        PenDown
//        Displacement(2y,0y)
//        Displacement(3y,1y)
//        Displacement(2y,1y)
//        Displacement(2y,1y)
//        Displacement(4y,4y)
//        Displacement(2y,4y)
//        Displacement(1y,5y)
//        Displacement(-1y,5y)
//        Displacement(-2y,4y)
//        Displacement(-4y,4y)
//        Displacement(-2y,1y)
//        Displacement(-2y,1y)
//        Displacement(-3y,1y)
//        Displacement(-2y,0y)
//        Displacement(-2y,0y)
//        Displacement(-3y,-1y)
//        Displacement(-2y,-1y)
//        Displacement(-2y,-1y)
//        Displacement(-4y,-4y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-5y)
//        Displacement(1y,-5y)
//        Displacement(2y,-4y)
//        Displacement(4y,-4y)
//        Displacement(2y,-1y)
//        Displacement(2y,-1y)
//        Displacement(3y,-1y)
//        Displacement(2y,0y)
//    ]
//    // ·
//    dict.[41380us] <- [
//        PenUp
//        Displacement(72y,50y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(-4y,4y)
//        PenDown
//        Displacement(26y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-30y,0y)
//        PenUp
//        Displacement(31y,5y)
//        PenDown
//        Displacement(-32y,0y)
//        PenUp
//        Displacement(1y,5y)
//        PenDown
//        Displacement(30y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-26y,0y)
//        PenUp
//        Displacement(4y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-9y,-29y)
//        PenDown
//        Displacement(2y,0y)
//        Displacement(3y,1y)
//        Displacement(2y,1y)
//        Displacement(2y,1y)
//        Displacement(4y,4y)
//        Displacement(2y,4y)
//        Displacement(1y,5y)
//        Displacement(-1y,5y)
//        Displacement(-2y,4y)
//        Displacement(-4y,4y)
//        Displacement(-2y,1y)
//        Displacement(-2y,1y)
//        Displacement(-3y,1y)
//        Displacement(-2y,0y)
//        Displacement(-2y,0y)
//        Displacement(-3y,-1y)
//        Displacement(-2y,-1y)
//        Displacement(-2y,-1y)
//        Displacement(-4y,-4y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-5y)
//        Displacement(1y,-5y)
//        Displacement(2y,-4y)
//        Displacement(4y,-4y)
//        Displacement(2y,-1y)
//        Displacement(2y,-1y)
//        Displacement(3y,-1y)
//        Displacement(2y,0y)
//    ]
//    // ˉ
//    dict.[41381us] <- [
//        PenUp
//        Displacement(48y,120y)
//        PenDown
//        Displacement(32y,0y)
//    ]
//    // ˇ
//    dict.[41382us] <- [
//        PenUp
//        Displacement(34y,124y)
//        PenDown
//        Displacement(30y,-20y)
//        Displacement(30y,20y)
//    ]
//    // ¨
//    dict.[41383us] <- [
//        PenUp
//        Displacement(28y,116y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(52y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(17y,7y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(1y,-3y)
//        PenDown
//        Displacement(-20y,0y)
//        PenUp
//        Displacement(1y,-3y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(-38y,0y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(1y,3y)
//        PenDown
//        Displacement(-20y,0y)
//        PenUp
//        Displacement(1y,3y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-14y,0y)
//    ]
//    // 〃
//    dict.[41384us] <- [
//        PenUp
//        Displacement(36y,35y)
//        PenDown
//        Displacement(20y,45y)
//        Displacement(-10y,3y)
//        Displacement(-10y,-48y)
//        PenUp
//        Displacement(36y,0y)
//        PenDown
//        Displacement(20y,45y)
//        Displacement(-10y,3y)
//        Displacement(-10y,-48y)
//        PenUp
//        Displacement(-30y,19y)
//        PenDown
//        Displacement(9y,27y)
//        PenUp
//        Displacement(36y,0y)
//        PenDown
//        Displacement(-9y,-27y)
//    ]
//    // 々
//    dict.[41385us] <- [
//        PenUp
//        Displacement(59y,105y)
//        PenDown
//        Displacement(2y,-9y)
//        Displacement(-13y,-17y)
//        Displacement(-8y,-8y)
//        Displacement(-10y,-9y)
//        PenUp
//        Displacement(13y,12y)
//        PenDown
//        Displacement(47y,0y)
//        PenUp
//        Displacement(7y,5y)
//        PenDown
//        Displacement(-7y,-5y)
//        Displacement(-31y,-40y)
//        PenUp
//        Displacement(-12y,11y)
//        PenDown
//        Displacement(8y,-7y)
//        Displacement(8y,-9y)
//        Displacement(3y,-7y)
//    ]
//    // —
//    dict.[41386us] <- [
//        PenUp
//        Displacement(1y,64y)
//        PenDown
//        Displacement(126y,0y)
//    ]
//    // ～
//    dict.[41387us] <- [
//        PenUp
//        Displacement(17y,56y)
//        PenDown
//        Displacement(10y,6y)
//        Displacement(9y,4y)
//        Displacement(9y,2y)
//        Displacement(4y,0y)
//        Displacement(7y,-2y)
//        Displacement(18y,-6y)
//        Displacement(5y,-1y)
//        Displacement(4y,0y)
//        Displacement(9y,2y)
//        Displacement(9y,4y)
//        Displacement(8y,6y)
//    ]
//    // ‖
//    dict.[41388us] <- [
//        PenUp
//        Displacement(49y,109y)
//        PenDown
//        Displacement(0y,-90y)
//        PenUp
//        Displacement(30y,0y)
//        PenDown
//        Displacement(0y,90y)
//    ]
//    // …
//    dict.[41389us] <- [
//        PenUp
//        Displacement(11y,64y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(43y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(43y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-83y,-6y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(57y,0y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(2y,-4y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(29y,0y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(0y,12y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(-18y,0y)
//    ]
//    // ‘
//    dict.[41390us] <- [
//        PenUp
//        Displacement(86y,101y)
//        PenDown
//        Displacement(0y,-6y)
//        PenUp
//        Displacement(12y,26y)
//        PenDown
//        Displacement(-7y,-13y)
//        PenUp
//        Displacement(11y,-17y)
//        PenDown
//        Displacement(0y,12y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(-4y,-1y)
//        PenDown
//        Displacement(0y,17y)
//        PenUp
//        Displacement(-4y,-16y)
//        PenDown
//        Displacement(0y,22y)
//        PenUp
//        Displacement(10y,14y)
//        PenDown
//        Displacement(-11y,-15y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(1y,-4y)
//        Displacement(4y,-5y)
//        Displacement(4y,-1y)
//        Displacement(2y,0y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(1y,3y)
//        Displacement(0y,6y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-6y,1y)
//        Displacement(2y,7y)
//        Displacement(2y,4y)
//        Displacement(2y,4y)
//        Displacement(1y,4y)
//    ]
//    // ’
//    dict.[41391us] <- [
//        PenUp
//        Displacement(27y,89y)
//        PenDown
//        Displacement(12y,14y)
//        Displacement(2y,4y)
//        Displacement(1y,3y)
//        Displacement(1y,4y)
//        Displacement(0y,4y)
//        Displacement(-4y,6y)
//        Displacement(-4y,1y)
//        Displacement(-2y,0y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-1y)
//        Displacement(-2y,-4y)
//        Displacement(0y,-5y)
//        Displacement(2y,-3y)
//        Displacement(3y,-3y)
//        Displacement(6y,-1y)
//        Displacement(-3y,-7y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-2y)
//        Displacement(-2y,-5y)
//        PenUp
//        Displacement(1y,20y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,1y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(4y,16y)
//        PenDown
//        Displacement(0y,-24y)
//        PenUp
//        Displacement(4y,5y)
//        PenDown
//        Displacement(0y,17y)
//        PenUp
//        Displacement(-10y,-28y)
//        PenDown
//        Displacement(8y,13y)
//    ]
//    // “
//    dict.[41392us] <- [
//        PenUp
//        Displacement(83y,126y)
//        PenDown
//        Displacement(-11y,-15y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(1y,-4y)
//        Displacement(4y,-5y)
//        Displacement(4y,-1y)
//        Displacement(2y,0y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(1y,3y)
//        Displacement(0y,6y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-6y,1y)
//        Displacement(2y,7y)
//        Displacement(2y,4y)
//        Displacement(2y,4y)
//        Displacement(1y,4y)
//        PenUp
//        Displacement(-11y,-34y)
//        PenDown
//        Displacement(0y,19y)
//        PenUp
//        Displacement(4y,5y)
//        PenDown
//        Displacement(0y,-26y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,16y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-13y)
//        PenUp
//        Displacement(-3y,31y)
//        PenDown
//        Displacement(-4y,-7y)
//        PenUp
//        Displacement(30y,7y)
//        PenDown
//        Displacement(-4y,-7y)
//        PenUp
//        Displacement(-5y,-23y)
//        PenDown
//        Displacement(0y,19y)
//        PenUp
//        Displacement(4y,5y)
//        PenDown
//        Displacement(0y,-26y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,16y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-13y)
//        PenUp
//        Displacement(-1y,35y)
//        PenDown
//        Displacement(-11y,-15y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(1y,-4y)
//        Displacement(4y,-5y)
//        Displacement(4y,-1y)
//        Displacement(2y,0y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(1y,3y)
//        Displacement(0y,6y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-6y,1y)
//        Displacement(2y,7y)
//        Displacement(2y,4y)
//        Displacement(2y,4y)
//        Displacement(1y,4y)
//    ]
//    // ”
//    dict.[41393us] <- [
//        PenUp
//        Displacement(46y,89y)
//        PenDown
//        Displacement(12y,14y)
//        Displacement(2y,4y)
//        Displacement(1y,3y)
//        Displacement(1y,4y)
//        Displacement(0y,4y)
//        Displacement(-4y,6y)
//        Displacement(-4y,1y)
//        Displacement(-2y,0y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-1y)
//        Displacement(-2y,-4y)
//        Displacement(0y,-5y)
//        Displacement(2y,-3y)
//        Displacement(3y,-3y)
//        Displacement(6y,-1y)
//        Displacement(-3y,-7y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-2y)
//        Displacement(-2y,-5y)
//        PenUp
//        Displacement(-28y,0y)
//        PenDown
//        Displacement(12y,14y)
//        Displacement(2y,4y)
//        Displacement(1y,3y)
//        Displacement(1y,4y)
//        Displacement(0y,4y)
//        Displacement(-4y,6y)
//        Displacement(-4y,1y)
//        Displacement(-2y,0y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-1y)
//        Displacement(-2y,-4y)
//        Displacement(0y,-5y)
//        Displacement(2y,-3y)
//        Displacement(3y,-3y)
//        Displacement(6y,-1y)
//        Displacement(-3y,-7y)
//        Displacement(-2y,-4y)
//        Displacement(-1y,-2y)
//        Displacement(-2y,-5y)
//        PenUp
//        Displacement(1y,20y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,1y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(4y,-8y)
//        PenDown
//        Displacement(0y,24y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(-8y,-9y)
//        PenDown
//        Displacement(4y,6y)
//        PenUp
//        Displacement(24y,-6y)
//        PenDown
//        Displacement(4y,6y)
//        PenUp
//        Displacement(0y,-3y)
//        PenDown
//        Displacement(0y,24y)
//        PenUp
//        Displacement(-8y,-15y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,1y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(8y,14y)
//        PenDown
//        Displacement(0y,-16y)
//    ]
//    // 〔
//    dict.[41394us] <- [
//        PenUp
//        Displacement(118y,118y)
//        PenDown
//        Displacement(-39y,-20y)
//        Displacement(0y,-68y)
//        Displacement(39y,-20y)
//    ]
//    // 〕
//    dict.[41395us] <- [
//        PenUp
//        Displacement(10y,118y)
//        PenDown
//        Displacement(39y,-20y)
//        Displacement(0y,-68y)
//        Displacement(-39y,-20y)
//    ]
//    // 〈
//    dict.[41396us] <- [
//        PenUp
//        Displacement(112y,111y)
//        PenDown
//        Displacement(-24y,-47y)
//        Displacement(24y,-50y)
//    ]
//    // 〉
//    dict.[41397us] <- [
//        PenUp
//        Displacement(16y,111y)
//        PenDown
//        Displacement(24y,-47y)
//        Displacement(-24y,-50y)
//    ]
//    // 《
//    dict.[41398us] <- [
//        PenUp
//        Displacement(118y,111y)
//        PenDown
//        Displacement(-26y,-48y)
//        Displacement(26y,-51y)
//        PenUp
//        Displacement(-30y,99y)
//        PenDown
//        Displacement(-26y,-48y)
//        Displacement(26y,-51y)
//    ]
//    // 》
//    dict.[41399us] <- [
//        PenUp
//        Displacement(10y,111y)
//        PenDown
//        Displacement(26y,-48y)
//        Displacement(-26y,-51y)
//        PenUp
//        Displacement(30y,99y)
//        PenDown
//        Displacement(26y,-48y)
//        Displacement(-26y,-51y)
//    ]
//    // 「
//    dict.[41400us] <- [
//        PenUp
//        Displacement(110y,124y)
//        PenDown
//        Displacement(-20y,0y)
//        Displacement(0y,-79y)
//    ]
//    // 」
//    dict.[41401us] <- [
//        PenUp
//        Displacement(15y,4y)
//        PenDown
//        Displacement(20y,0y)
//        Displacement(0y,79y)
//    ]
//    // 『
//    dict.[41402us] <- [
//        PenUp
//        Displacement(87y,48y)
//        PenDown
//        Displacement(0y,76y)
//        Displacement(26y,0y)
//        Displacement(0y,-8y)
//        Displacement(-16y,0y)
//        Displacement(0y,-68y)
//        Displacement(-10y,0y)
//    ]
//    // 』
//    dict.[41403us] <- [
//        PenUp
//        Displacement(15y,4y)
//        PenDown
//        Displacement(0y,8y)
//        Displacement(18y,0y)
//        Displacement(0y,68y)
//        Displacement(10y,0y)
//        Displacement(0y,-76y)
//        Displacement(-28y,0y)
//    ]
//    // 〖
//    dict.[41404us] <- [
//        PenUp
//        Displacement(71y,17y)
//        PenDown
//        Displacement(0y,94y)
//        Displacement(42y,0y)
//        Displacement(-11y,-20y)
//        Displacement(-6y,-12y)
//        Displacement(-3y,-8y)
//        Displacement(-1y,-7y)
//        Displacement(2y,-12y)
//        Displacement(4y,-10y)
//        Displacement(6y,-11y)
//        Displacement(9y,-14y)
//        Displacement(-42y,0y)
//    ]
//    // 〗
//    dict.[41405us] <- [
//        PenUp
//        Displacement(57y,17y)
//        PenDown
//        Displacement(0y,94y)
//        Displacement(-42y,0y)
//        Displacement(11y,-20y)
//        Displacement(6y,-12y)
//        Displacement(3y,-8y)
//        Displacement(1y,-7y)
//        Displacement(-2y,-12y)
//        Displacement(-4y,-10y)
//        Displacement(-6y,-11y)
//        Displacement(-9y,-14y)
//        Displacement(42y,0y)
//    ]
//    // 【
//    dict.[41406us] <- [
//        PenUp
//        Displacement(72y,117y)
//        PenDown
//        Displacement(41y,0y)
//        Displacement(-11y,-13y)
//        Displacement(-6y,-10y)
//        Displacement(-6y,-11y)
//        Displacement(-3y,-8y)
//        Displacement(-1y,-7y)
//        Displacement(1y,-8y)
//        Displacement(4y,-12y)
//        Displacement(5y,-11y)
//        Displacement(17y,-25y)
//        Displacement(-41y,0y)
//        Displacement(0y,105y)
//        PenUp
//        Displacement(0y,-101y)
//        PenDown
//        Displacement(38y,0y)
//        PenUp
//        Displacement(-3y,4y)
//        PenDown
//        Displacement(-35y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(32y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-30y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(27y,0y)
//        PenUp
//        Displacement(-27y,4y)
//        PenDown
//        Displacement(24y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-22y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(21y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-19y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(17y,0y)
//        PenUp
//        Displacement(-1y,4y)
//        PenDown
//        Displacement(-16y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(15y,0y)
//        PenUp
//        Displacement(-1y,4y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(15y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-17y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-20y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(23y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-25y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(27y,0y)
//        PenUp
//        Displacement(3y,4y)
//        PenDown
//        Displacement(-30y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(33y,0y)
//        PenUp
//        Displacement(3y,4y)
//        PenDown
//        Displacement(-36y,0y)
//        PenUp
//        Displacement(0y,3y)
//        PenDown
//        Displacement(39y,0y)
//    ]
//    // 】
//    dict.[41407us] <- [
//        PenUp
//        Displacement(56y,117y)
//        PenDown
//        Displacement(-41y,0y)
//        Displacement(11y,-13y)
//        Displacement(6y,-10y)
//        Displacement(6y,-11y)
//        Displacement(3y,-8y)
//        Displacement(1y,-7y)
//        Displacement(-1y,-8y)
//        Displacement(-4y,-12y)
//        Displacement(-5y,-11y)
//        Displacement(-17y,-25y)
//        Displacement(41y,0y)
//        Displacement(0y,105y)
//        PenUp
//        Displacement(0y,-101y)
//        PenDown
//        Displacement(-38y,0y)
//        PenUp
//        Displacement(3y,4y)
//        PenDown
//        Displacement(35y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-32y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(30y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-27y,0y)
//        PenUp
//        Displacement(27y,4y)
//        PenDown
//        Displacement(-24y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(22y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-21y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(19y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-17y,0y)
//        PenUp
//        Displacement(1y,4y)
//        PenDown
//        Displacement(16y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-15y,0y)
//        PenUp
//        Displacement(1y,4y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-15y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(17y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(20y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-23y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(25y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-27y,0y)
//        PenUp
//        Displacement(-3y,4y)
//        PenDown
//        Displacement(30y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-33y,0y)
//        PenUp
//        Displacement(-3y,4y)
//        PenDown
//        Displacement(36y,0y)
//        PenUp
//        Displacement(0y,3y)
//        PenDown
//        Displacement(-39y,0y)
//    ]
//    // ±
//    dict.[41408us] <- [
//        PenUp
//        Displacement(20y,68y)
//        PenDown
//        Displacement(86y,0y)
//        PenUp
//        Displacement(-42y,36y)
//        PenDown
//        Displacement(0y,-66y)
//        PenUp
//        Displacement(-44y,-16y)
//        PenDown
//        Displacement(84y,0y)
//    ]
//    // ×
//    dict.[41409us] <- [
//        PenUp
//        Displacement(24y,103y)
//        PenDown
//        Displacement(78y,-79y)
//        PenUp
//        Displacement(-78y,0y)
//        PenDown
//        Displacement(78y,79y)
//    ]
//    // ÷
//    dict.[41410us] <- [
//        PenUp
//        Displacement(57y,95y)
//        PenDown
//        Displacement(1y,4y)
//        Displacement(2y,2y)
//        Displacement(2y,1y)
//        Displacement(4y,0y)
//        Displacement(2y,-1y)
//        Displacement(2y,-2y)
//        Displacement(1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-2y,-2y)
//        Displacement(-2y,-1y)
//        Displacement(-4y,0y)
//        Displacement(-2y,1y)
//        Displacement(-2y,2y)
//        Displacement(-1y,4y)
//        PenUp
//        Displacement(-40y,-31y)
//        PenDown
//        Displacement(90y,0y)
//        PenUp
//        Displacement(-47y,25y)
//        PenDown
//        Displacement(0y,12y)
//        PenUp
//        Displacement(4y,1y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(4y,1y)
//        PenDown
//        Displacement(0y,12y)
//        PenUp
//        Displacement(0y,-74y)
//        PenDown
//        Displacement(0y,12y)
//        PenUp
//        Displacement(-4y,1y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,1y)
//        PenDown
//        Displacement(0y,12y)
//        PenUp
//        Displacement(-3y,-6y)
//        PenDown
//        Displacement(1y,4y)
//        Displacement(2y,2y)
//        Displacement(2y,1y)
//        Displacement(4y,0y)
//        Displacement(2y,-1y)
//        Displacement(2y,-2y)
//        Displacement(1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-2y,-2y)
//        Displacement(-2y,-1y)
//        Displacement(-4y,0y)
//        Displacement(-2y,1y)
//        Displacement(-2y,2y)
//        Displacement(-1y,4y)
//    ]
//    // ∶
//    dict.[41411us] <- [
//        PenUp
//        Displacement(54y,32y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(0y,64y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(3y,-6y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-16y,4y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(-14y,-64y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(-16y,-4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(2y,-4y)
//        PenDown
//        Displacement(14y,0y)
//    ]
//    // ∧
//    dict.[41412us] <- [
//        PenUp
//        Displacement(15y,13y)
//        PenDown
//        Displacement(49y,102y)
//        Displacement(49y,-102y)
//    ]
//    // ∨
//    dict.[41413us] <- [
//        PenUp
//        Displacement(15y,115y)
//        PenDown
//        Displacement(49y,-102y)
//        Displacement(49y,102y)
//    ]
//    // ∑
//    dict.[41414us] <- [
//        PenUp
//        Displacement(110y,121y)
//        PenDown
//        Displacement(4y,-25y)
//        Displacement(0y,25y)
//        Displacement(-99y,0y)
//        Displacement(55y,-56y)
//        Displacement(-55y,-58y)
//        Displacement(99y,0y)
//        Displacement(0y,27y)
//        Displacement(-4y,-23y)
//        Displacement(-91y,0y)
//        PenUp
//        Displacement(2y,110y)
//        PenDown
//        Displacement(55y,-56y)
//    ]
//    // ∏
//    dict.[41415us] <- [
//        PenUp
//        Displacement(8y,124y)
//        PenDown
//        Displacement(110y,0y)
//        PenUp
//        Displacement(-85y,0y)
//        PenDown
//        Displacement(0y,-121y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,121y)
//        PenUp
//        Displacement(-14y,-121y)
//        PenDown
//        Displacement(24y,0y)
//        PenUp
//        Displacement(33y,0y)
//        PenDown
//        Displacement(24y,0y)
//        PenUp
//        Displacement(-10y,0y)
//        PenDown
//        Displacement(0y,121y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-121y)
//    ]
//    // ∪
//    dict.[41416us] <- [
//        PenUp
//        Displacement(12y,125y)
//        PenDown
//        Displacement(0y,-68y)
//        Displacement(3y,-18y)
//        Displacement(8y,-14y)
//        Displacement(11y,-10y)
//        Displacement(11y,-7y)
//        Displacement(19y,-4y)
//        Displacement(19y,4y)
//        Displacement(11y,7y)
//        Displacement(11y,10y)
//        Displacement(8y,14y)
//        Displacement(3y,18y)
//        Displacement(0y,68y)
//    ]
//    // ∩
//    dict.[41417us] <- [
//        PenUp
//        Displacement(116y,1y)
//        PenDown
//        Displacement(0y,68y)
//        Displacement(-3y,18y)
//        Displacement(-8y,14y)
//        Displacement(-11y,10y)
//        Displacement(-11y,7y)
//        Displacement(-19y,4y)
//        Displacement(-19y,-4y)
//        Displacement(-11y,-7y)
//        Displacement(-11y,-10y)
//        Displacement(-8y,-14y)
//        Displacement(-3y,-18y)
//        Displacement(0y,-68y)
//    ]
//    // ∈
//    dict.[41418us] <- [
//        PenUp
//        Displacement(87y,18y)
//        PenDown
//        Displacement(-12y,2y)
//        Displacement(-12y,4y)
//        Displacement(-8y,6y)
//        Displacement(-8y,10y)
//        Displacement(-4y,10y)
//        Displacement(-2y,14y)
//        Displacement(2y,14y)
//        Displacement(4y,10y)
//        Displacement(8y,10y)
//        Displacement(8y,6y)
//        Displacement(12y,4y)
//        Displacement(12y,2y)
//        PenUp
//        Displacement(-46y,-46y)
//        PenDown
//        Displacement(45y,0y)
//    ]
//    // ∷
//    dict.[41419us] <- [
//        PenUp
//        Displacement(86y,93y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-64y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(0y,-59y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(64y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-60y,-7y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(0y,73y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(76y,0y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(12y,-59y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//    ]
//    // √
//    dict.[41420us] <- [
//        PenUp
//        Displacement(8y,36y)
//        PenDown
//        Displacement(17y,15y)
//        Displacement(35y,-47y)
//        Displacement(63y,123y)
//    ]
//    // ⊥
//    dict.[41421us] <- [
//        PenUp
//        Displacement(18y,24y)
//        PenDown
//        Displacement(92y,0y)
//        PenUp
//        Displacement(-46y,0y)
//        PenDown
//        Displacement(0y,81y)
//    ]
//    // ∥
//    dict.[41422us] <- [
//        PenUp
//        Displacement(23y,23y)
//        PenDown
//        Displacement(52y,85y)
//        PenUp
//        Displacement(30y,0y)
//        PenDown
//        Displacement(-52y,-85y)
//    ]
//    // ∠
//    dict.[41423us] <- [
//        PenUp
//        Displacement(118y,107y)
//        PenDown
//        Displacement(-85y,-86y)
//        Displacement(86y,0y)
//    ]
//    // ⌒
//    dict.[41424us] <- [
//        PenUp
//        Displacement(103y,108y)
//        PenDown
//        Displacement(-11y,7y)
//        Displacement(-8y,4y)
//        Displacement(-11y,4y)
//        Displacement(-9y,1y)
//        Displacement(-9y,-1y)
//        Displacement(-11y,-4y)
//        Displacement(-8y,-4y)
//        Displacement(-11y,-7y)
//    ]
//    // ⊙
//    dict.[41425us] <- [
//        PenUp
//        Displacement(54y,64y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-47y,0y)
//        PenDown
//        Displacement(2y,12y)
//        Displacement(4y,12y)
//        Displacement(8y,12y)
//        Displacement(12y,11y)
//        Displacement(16y,7y)
//        Displacement(15y,3y)
//        Displacement(15y,-3y)
//        Displacement(16y,-7y)
//        Displacement(12y,-11y)
//        Displacement(8y,-12y)
//        Displacement(4y,-12y)
//        Displacement(2y,-12y)
//        Displacement(-2y,-12y)
//        Displacement(-4y,-12y)
//        Displacement(-8y,-12y)
//        Displacement(-12y,-11y)
//        Displacement(-16y,-7y)
//        Displacement(-15y,-3y)
//        Displacement(-15y,3y)
//        Displacement(-16y,7y)
//        Displacement(-12y,11y)
//        Displacement(-8y,12y)
//        Displacement(-4y,12y)
//        Displacement(-2y,12y)
//        PenUp
//        Displacement(50y,-6y)
//        PenDown
//        Displacement(14y,0y)
//        PenUp
//        Displacement(2y,4y)
//        PenDown
//        Displacement(-18y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(18y,0y)
//        PenUp
//        Displacement(-2y,4y)
//        PenDown
//        Displacement(-14y,0y)
//    ]
//    // ∫
//    dict.[41426us] <- [
//        PenUp
//        Displacement(109y,122y)
//        PenDown
//        Displacement(-3y,-1y)
//        Displacement(-1y,-3y)
//        Displacement(1y,-3y)
//        Displacement(3y,-1y)
//        Displacement(3y,1y)
//        Displacement(1y,3y)
//        Displacement(-1y,3y)
//        Displacement(-6y,2y)
//        Displacement(-4y,0y)
//        Displacement(-7y,-3y)
//        Displacement(-4y,-7y)
//        Displacement(-3y,-12y)
//        Displacement(-4y,-74y)
//        Displacement(-3y,-12y)
//        Displacement(-4y,-7y)
//        Displacement(-7y,-3y)
//        Displacement(-4y,0y)
//        Displacement(-6y,2y)
//        Displacement(-1y,3y)
//        Displacement(1y,3y)
//        Displacement(3y,1y)
//        Displacement(3y,-1y)
//        Displacement(1y,-3y)
//        Displacement(-1y,-3y)
//        Displacement(-3y,-1y)
//    ]
//    // ∮
//    dict.[41427us] <- [
//        PenUp
//        Displacement(109y,122y)
//        PenDown
//        Displacement(-3y,-1y)
//        Displacement(-1y,-3y)
//        Displacement(1y,-3y)
//        Displacement(3y,-1y)
//        Displacement(3y,1y)
//        Displacement(1y,3y)
//        Displacement(-1y,3y)
//        Displacement(-6y,2y)
//        Displacement(-4y,0y)
//        Displacement(-7y,-3y)
//        Displacement(-4y,-7y)
//        Displacement(-3y,-12y)
//        Displacement(-4y,-74y)
//        Displacement(-3y,-12y)
//        Displacement(-4y,-7y)
//        Displacement(-7y,-3y)
//        Displacement(-4y,0y)
//        Displacement(-6y,2y)
//        Displacement(-1y,3y)
//        Displacement(1y,3y)
//        Displacement(3y,1y)
//        Displacement(3y,-1y)
//        Displacement(1y,-3y)
//        Displacement(-1y,-3y)
//        Displacement(-3y,-1y)
//        PenUp
//        Displacement(24y,71y)
//        PenDown
//        Displacement(-10y,-1y)
//        Displacement(-6y,-3y)
//        Displacement(-3y,-3y)
//        Displacement(-2y,-4y)
//        Displacement(0y,-4y)
//        Displacement(2y,-4y)
//        Displacement(3y,-3y)
//        Displacement(6y,-3y)
//        Displacement(10y,-1y)
//        Displacement(10y,1y)
//        Displacement(6y,3y)
//        Displacement(3y,3y)
//        Displacement(2y,4y)
//        Displacement(0y,4y)
//        Displacement(-2y,4y)
//        Displacement(-3y,3y)
//        Displacement(-6y,3y)
//        Displacement(-10y,1y)
//    ]
//    // ≡
//    dict.[41428us] <- [
//        PenUp
//        Displacement(20y,44y)
//        PenDown
//        Displacement(88y,0y)
//        PenUp
//        Displacement(-88y,20y)
//        PenDown
//        Displacement(88y,0y)
//        PenUp
//        Displacement(-88y,20y)
//        PenDown
//        Displacement(88y,0y)
//    ]
//    // ≌
//    dict.[41429us] <- [
//        PenUp
//        Displacement(17y,29y)
//        PenDown
//        Displacement(98y,0y)
//        PenUp
//        Displacement(-98y,24y)
//        PenDown
//        Displacement(98y,0y)
//        PenUp
//        Displacement(-70y,45y)
//        PenDown
//        Displacement(-5y,0y)
//        Displacement(-5y,-1y)
//        Displacement(-6y,-3y)
//        Displacement(-4y,-4y)
//        Displacement(-3y,-6y)
//        Displacement(0y,-8y)
//        Displacement(3y,-7y)
//        Displacement(4y,-3y)
//        Displacement(7y,-3y)
//        Displacement(7y,0y)
//        Displacement(6y,3y)
//        Displacement(7y,6y)
//        Displacement(20y,17y)
//        Displacement(7y,6y)
//        Displacement(6y,3y)
//        Displacement(7y,0y)
//        Displacement(7y,-3y)
//        Displacement(4y,-3y)
//        Displacement(3y,-7y)
//        Displacement(0y,-8y)
//        Displacement(-3y,-6y)
//        Displacement(-4y,-4y)
//        Displacement(-6y,-3y)
//        Displacement(-5y,-1y)
//        Displacement(-5y,0y)
//    ]
//    // ≈
//    dict.[41430us] <- [
//        PenUp
//        Displacement(16y,69y)
//        PenDown
//        Displacement(10y,11y)
//        Displacement(9y,7y)
//        Displacement(7y,2y)
//        Displacement(7y,-2y)
//        Displacement(28y,-16y)
//        Displacement(7y,-2y)
//        Displacement(7y,2y)
//        Displacement(9y,6y)
//        Displacement(10y,11y)
//        PenUp
//        Displacement(-94y,-48y)
//        PenDown
//        Displacement(10y,11y)
//        Displacement(9y,7y)
//        Displacement(7y,2y)
//        Displacement(7y,-2y)
//        Displacement(28y,-16y)
//        Displacement(7y,-2y)
//        Displacement(7y,2y)
//        Displacement(9y,6y)
//        Displacement(10y,11y)
//    ]
//    // ∽
//    dict.[41431us] <- [
//        PenUp
//        Displacement(41y,41y)
//        PenDown
//        Displacement(-5y,0y)
//        Displacement(-5y,1y)
//        Displacement(-6y,3y)
//        Displacement(-5y,4y)
//        Displacement(-3y,5y)
//        Displacement(-2y,8y)
//        Displacement(0y,6y)
//        Displacement(2y,6y)
//        Displacement(4y,6y)
//        Displacement(5y,4y)
//        Displacement(6y,2y)
//        Displacement(7y,0y)
//        Displacement(6y,-2y)
//        Displacement(7y,-7y)
//        Displacement(25y,-27y)
//        Displacement(7y,-7y)
//        Displacement(6y,-2y)
//        Displacement(7y,0y)
//        Displacement(6y,2y)
//        Displacement(5y,4y)
//        Displacement(4y,6y)
//        Displacement(2y,6y)
//        Displacement(0y,6y)
//        Displacement(-2y,8y)
//        Displacement(-3y,5y)
//        Displacement(-5y,4y)
//        Displacement(-6y,3y)
//        Displacement(-5y,1y)
//        Displacement(-5y,0y)
//    ]
//    // ∝
//    dict.[41432us] <- [
//        PenUp
//        Displacement(107y,47y)
//        PenDown
//        Displacement(-5y,-4y)
//        Displacement(-6y,-2y)
//        Displacement(-7y,0y)
//        Displacement(-6y,2y)
//        Displacement(-7y,5y)
//        Displacement(-5y,5y)
//        Displacement(-4y,6y)
//        Displacement(-4y,6y)
//        Displacement(-4y,6y)
//        Displacement(-4y,6y)
//        Displacement(-6y,6y)
//        Displacement(-5y,3y)
//        Displacement(-6y,2y)
//        Displacement(-7y,0y)
//        Displacement(-6y,-2y)
//        Displacement(-5y,-4y)
//        Displacement(-4y,-5y)
//        Displacement(-3y,-6y)
//        Displacement(-1y,-7y)
//        Displacement(1y,-7y)
//        Displacement(3y,-6y)
//        Displacement(4y,-5y)
//        Displacement(5y,-4y)
//        Displacement(6y,-2y)
//        Displacement(7y,0y)
//        Displacement(6y,2y)
//        Displacement(5y,3y)
//        Displacement(6y,6y)
//        Displacement(4y,6y)
//        Displacement(4y,6y)
//        Displacement(4y,6y)
//        Displacement(4y,6y)
//        Displacement(5y,5y)
//        Displacement(7y,5y)
//        Displacement(6y,2y)
//        Displacement(7y,0y)
//        Displacement(6y,-2y)
//        Displacement(5y,-4y)
//    ]
//    // ≠
//    dict.[41433us] <- [
//        PenUp
//        Displacement(10y,81y)
//        PenDown
//        Displacement(107y,0y)
//        PenUp
//        Displacement(-107y,-35y)
//        PenDown
//        Displacement(107y,0y)
//        PenUp
//        Displacement(-36y,68y)
//        PenDown
//        Displacement(-39y,-106y)
//    ]
//    // ≮
//    dict.[41434us] <- [
//        PenUp
//        Displacement(64y,114y)
//        PenDown
//        Displacement(0y,-103y)
//        PenUp
//        Displacement(52y,102y)
//        PenDown
//        Displacement(-103y,-49y)
//        Displacement(103y,-37y)
//    ]
//    // ≯
//    dict.[41435us] <- [
//        PenUp
//        Displacement(64y,114y)
//        PenDown
//        Displacement(0y,-103y)
//        PenUp
//        Displacement(-52y,102y)
//        PenDown
//        Displacement(103y,-49y)
//        Displacement(-103y,-37y)
//    ]
//    // ≤
//    dict.[41436us] <- [
//        PenUp
//        Displacement(115y,113y)
//        PenDown
//        Displacement(-102y,-49y)
//        Displacement(102y,-37y)
//        PenUp
//        Displacement(-101y,-13y)
//        PenDown
//        Displacement(101y,0y)
//    ]
//    // ≥
//    dict.[41437us] <- [
//        PenUp
//        Displacement(11y,113y)
//        PenDown
//        Displacement(102y,-49y)
//        Displacement(-102y,-37y)
//        PenUp
//        Displacement(0y,-13y)
//        PenDown
//        Displacement(102y,0y)
//    ]
//    // ∞
//    dict.[41438us] <- [
//        PenUp
//        Displacement(70y,74y)
//        PenDown
//        Displacement(-12y,-20y)
//        Displacement(-7y,-7y)
//        Displacement(-8y,-5y)
//        Displacement(-8y,-2y)
//        Displacement(-2y,0y)
//        Displacement(-7y,2y)
//        Displacement(-7y,5y)
//        Displacement(-5y,7y)
//        Displacement(-2y,8y)
//        Displacement(0y,4y)
//        Displacement(2y,8y)
//        Displacement(5y,7y)
//        Displacement(7y,5y)
//        Displacement(7y,2y)
//        Displacement(2y,0y)
//        Displacement(8y,-2y)
//        Displacement(8y,-5y)
//        Displacement(7y,-7y)
//        Displacement(12y,-20y)
//        Displacement(7y,-7y)
//        Displacement(8y,-5y)
//        Displacement(8y,-2y)
//        Displacement(2y,0y)
//        Displacement(7y,2y)
//        Displacement(7y,5y)
//        Displacement(5y,7y)
//        Displacement(2y,8y)
//        Displacement(0y,4y)
//        Displacement(-2y,8y)
//        Displacement(-5y,7y)
//        Displacement(-7y,5y)
//        Displacement(-7y,2y)
//        Displacement(-2y,0y)
//        Displacement(-8y,-2y)
//        Displacement(-8y,-5y)
//        Displacement(-7y,-7y)
//    ]
//    // ∵
//    dict.[41439us] <- [
//        PenUp
//        Displacement(22y,92y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(64y,0y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-32y,-56y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(4y,-7y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-32y,70y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(76y,0y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//    ]
//    // ∴
//    dict.[41440us] <- [
//        PenUp
//        Displacement(22y,36y)
//        PenDown
//        Displacement(1y,4y)
//        Displacement(2y,3y)
//        Displacement(3y,2y)
//        Displacement(4y,1y)
//        Displacement(4y,-1y)
//        Displacement(3y,-2y)
//        Displacement(2y,-3y)
//        Displacement(1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-2y,-3y)
//        Displacement(-3y,-2y)
//        Displacement(-4y,-1y)
//        Displacement(-4y,1y)
//        Displacement(-3y,2y)
//        Displacement(-2y,3y)
//        Displacement(-1y,4y)
//        PenUp
//        Displacement(32y,56y)
//        PenDown
//        Displacement(1y,4y)
//        Displacement(2y,3y)
//        Displacement(3y,2y)
//        Displacement(4y,1y)
//        Displacement(4y,-1y)
//        Displacement(3y,-2y)
//        Displacement(2y,-3y)
//        Displacement(1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-2y,-3y)
//        Displacement(-3y,-2y)
//        Displacement(-4y,-1y)
//        Displacement(-4y,1y)
//        Displacement(-3y,2y)
//        Displacement(-2y,3y)
//        Displacement(-1y,4y)
//        PenUp
//        Displacement(32y,-56y)
//        PenDown
//        Displacement(1y,4y)
//        Displacement(2y,3y)
//        Displacement(3y,2y)
//        Displacement(4y,1y)
//        Displacement(4y,-1y)
//        Displacement(3y,-2y)
//        Displacement(2y,-3y)
//        Displacement(1y,-4y)
//        Displacement(-1y,-4y)
//        Displacement(-2y,-3y)
//        Displacement(-3y,-2y)
//        Displacement(-4y,-1y)
//        Displacement(-4y,1y)
//        Displacement(-3y,2y)
//        Displacement(-2y,3y)
//        Displacement(-1y,4y)
//        PenUp
//        Displacement(-60y,-7y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(32y,70y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(44y,-56y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//    ]
//    // ♂
//    dict.[41441us] <- [
//        PenUp
//        Displacement(46y,79y)
//        PenDown
//        Displacement(18y,21y)
//        Displacement(18y,-21y)
//        PenUp
//        Displacement(-18y,21y)
//        PenDown
//        Displacement(0y,-49y)
//        Displacement(-6y,-1y)
//        Displacement(-5y,-4y)
//        Displacement(-3y,-5y)
//        Displacement(-1y,-6y)
//        Displacement(1y,-6y)
//        Displacement(3y,-5y)
//        Displacement(5y,-4y)
//        Displacement(6y,-1y)
//        Displacement(6y,1y)
//        Displacement(5y,4y)
//        Displacement(3y,5y)
//        Displacement(1y,6y)
//        Displacement(-1y,6y)
//        Displacement(-3y,5y)
//        Displacement(-5y,4y)
//        Displacement(-6y,1y)
//    ]
//    // ♀
//    dict.[41442us] <- [
//        PenUp
//        Displacement(64y,12y)
//        PenDown
//        Displacement(0y,63y)
//        Displacement(-6y,1y)
//        Displacement(-5y,4y)
//        Displacement(-3y,5y)
//        Displacement(-1y,6y)
//        Displacement(1y,6y)
//        Displacement(3y,5y)
//        Displacement(5y,4y)
//        Displacement(6y,1y)
//        Displacement(6y,-1y)
//        Displacement(5y,-4y)
//        Displacement(3y,-5y)
//        Displacement(1y,-6y)
//        Displacement(-1y,-6y)
//        Displacement(-3y,-5y)
//        Displacement(-5y,-4y)
//        Displacement(-6y,-1y)
//        PenUp
//        Displacement(-30y,-25y)
//        PenDown
//        Displacement(59y,0y)
//    ]
//    // °
//    dict.[41443us] <- [
//        PenUp
//        Displacement(5y,111y)
//        PenDown
//        Displacement(2y,-6y)
//        Displacement(5y,-5y)
//        Displacement(6y,-2y)
//        Displacement(6y,2y)
//        Displacement(5y,5y)
//        Displacement(2y,6y)
//        Displacement(-2y,7y)
//        Displacement(-5y,4y)
//        Displacement(-6y,2y)
//        Displacement(-6y,-2y)
//        Displacement(-5y,-4y)
//        Displacement(-2y,-7y)
//    ]
//    // ′
//    dict.[41444us] <- [
//        PenUp
//        Displacement(22y,121y)
//        PenDown
//        Displacement(-1y,-2y)
//        Displacement(-14y,-27y)
//        Displacement(-2y,-1y)
//        Displacement(0y,1y)
//        Displacement(0y,1y)
//        Displacement(9y,30y)
//        Displacement(2y,1y)
//        Displacement(1y,0y)
//        Displacement(2y,0y)
//        Displacement(2y,-1y)
//        Displacement(1y,-2y)
//        PenUp
//        Displacement(-13y,-21y)
//        PenDown
//        Displacement(9y,23y)
//    ]
//    // ″
//    dict.[41445us] <- [
//        PenUp
//        Displacement(39y,121y)
//        PenDown
//        Displacement(-1y,-2y)
//        Displacement(-14y,-27y)
//        Displacement(-2y,-1y)
//        Displacement(0y,1y)
//        Displacement(0y,1y)
//        Displacement(9y,30y)
//        Displacement(2y,1y)
//        Displacement(1y,0y)
//        Displacement(2y,0y)
//        Displacement(2y,-1y)
//        Displacement(1y,-2y)
//        PenUp
//        Displacement(-17y,0y)
//        PenDown
//        Displacement(-1y,-2y)
//        Displacement(-14y,-27y)
//        Displacement(-2y,-1y)
//        Displacement(0y,1y)
//        Displacement(0y,1y)
//        Displacement(9y,30y)
//        Displacement(2y,1y)
//        Displacement(1y,0y)
//        Displacement(2y,0y)
//        Displacement(2y,-1y)
//        Displacement(1y,-2y)
//        PenUp
//        Displacement(-12y,-19y)
//        PenDown
//        Displacement(8y,21y)
//        PenUp
//        Displacement(17y,0y)
//        PenDown
//        Displacement(-8y,-21y)
//    ]
//    // ℃
//    dict.[41446us] <- [
//        PenUp
//        Displacement(10y,113y)
//        PenDown
//        Displacement(2y,-6y)
//        Displacement(6y,-5y)
//        Displacement(6y,0y)
//        Displacement(6y,5y)
//        Displacement(2y,6y)
//        Displacement(-2y,7y)
//        Displacement(-6y,4y)
//        Displacement(-6y,0y)
//        Displacement(-6y,-4y)
//        Displacement(-2y,-7y)
//        PenUp
//        Displacement(100y,-11y)
//        PenDown
//        Displacement(6y,12y)
//        Displacement(0y,-27y)
//        Displacement(-6y,15y)
//        Displacement(-4y,5y)
//        Displacement(-8y,5y)
//        Displacement(-8y,2y)
//        Displacement(-11y,0y)
//        Displacement(-9y,-5y)
//        Displacement(-8y,-7y)
//        Displacement(-7y,-12y)
//        Displacement(-4y,-15y)
//        Displacement(0y,-20y)
//        Displacement(4y,-17y)
//        Displacement(6y,-13y)
//        Displacement(8y,-8y)
//        Displacement(10y,-5y)
//        Displacement(11y,0y)
//        Displacement(7y,2y)
//        Displacement(7y,5y)
//        Displacement(5y,6y)
//        Displacement(5y,13y)
//        PenUp
//        Displacement(-35y,76y)
//        PenDown
//        Displacement(-8y,-7y)
//        Displacement(-5y,-6y)
//        Displacement(-7y,-12y)
//        Displacement(-3y,-14y)
//        Displacement(0y,-20y)
//        Displacement(3y,-16y)
//        Displacement(6y,-14y)
//        Displacement(6y,-7y)
//        Displacement(8y,-6y)
//    ]
//    // ＄
//    dict.[41447us] <- [
//        PenUp
//        Displacement(93y,94y)
//        PenDown
//        Displacement(-3y,1y)
//        Displacement(-3y,-1y)
//        Displacement(-1y,-3y)
//        Displacement(1y,-3y)
//        Displacement(3y,-1y)
//        Displacement(3y,1y)
//        Displacement(1y,3y)
//        Displacement(-1y,3y)
//        Displacement(-6y,7y)
//        Displacement(-7y,4y)
//        Displacement(-10y,2y)
//        Displacement(-12y,0y)
//        Displacement(-7y,-3y)
//        Displacement(-6y,-6y)
//        Displacement(-4y,-9y)
//        Displacement(0y,-8y)
//        Displacement(4y,-7y)
//        Displacement(6y,-4y)
//        Displacement(29y,-12y)
//        Displacement(6y,-5y)
//        Displacement(4y,-6y)
//        Displacement(0y,-11y)
//        Displacement(-4y,-7y)
//        Displacement(-6y,-5y)
//        Displacement(-7y,-3y)
//        Displacement(-12y,0y)
//        Displacement(-10y,2y)
//        Displacement(-7y,4y)
//        Displacement(-6y,7y)
//        Displacement(-1y,3y)
//        Displacement(1y,3y)
//        Displacement(3y,1y)
//        Displacement(3y,-1y)
//        Displacement(1y,-3y)
//        Displacement(-1y,-3y)
//        Displacement(-3y,-1y)
//        Displacement(-3y,1y)
//        PenUp
//        Displacement(26y,85y)
//        PenDown
//        Displacement(0y,-108y)
//        PenUp
//        Displacement(-6y,96y)
//        PenDown
//        Displacement(-4y,-3y)
//        Displacement(-6y,-6y)
//        Displacement(-3y,-9y)
//        Displacement(0y,-8y)
//        Displacement(2y,-5y)
//        Displacement(4y,-6y)
//        PenUp
//        Displacement(29y,-12y)
//        PenDown
//        Displacement(7y,-3y)
//        Displacement(7y,-8y)
//        Displacement(0y,-11y)
//        Displacement(-4y,-7y)
//        Displacement(-6y,-5y)
//        Displacement(-11y,-3y)
//    ]
//    // ¤
//    dict.[41448us] <- [
//        PenUp
//        Displacement(64y,102y)
//        PenDown
//        Displacement(-15y,-3y)
//        Displacement(-12y,-8y)
//        Displacement(-8y,-12y)
//        Displacement(-3y,-15y)
//        Displacement(3y,-14y)
//        Displacement(8y,-13y)
//        Displacement(12y,-8y)
//        Displacement(15y,-3y)
//        Displacement(15y,3y)
//        Displacement(12y,8y)
//        Displacement(8y,13y)
//        Displacement(3y,14y)
//        Displacement(-3y,15y)
//        Displacement(-8y,12y)
//        Displacement(-12y,8y)
//        Displacement(-15y,3y)
//        PenUp
//        Displacement(-39y,2y)
//        PenDown
//        Displacement(12y,-13y)
//        PenUp
//        Displacement(54y,-54y)
//        PenDown
//        Displacement(12y,-12y)
//        PenUp
//        Displacement(0y,79y)
//        PenDown
//        Displacement(-12y,-13y)
//        PenUp
//        Displacement(-54y,-54y)
//        PenDown
//        Displacement(-12y,-12y)
//    ]
//    // ￠
//    dict.[41449us] <- [
//        PenUp
//        Displacement(65y,113y)
//        PenDown
//        Displacement(-28y,-102y)
//        PenUp
//        Displacement(35y,79y)
//        PenDown
//        Displacement(5y,9y)
//        Displacement(0y,-20y)
//        Displacement(-5y,11y)
//        Displacement(-5y,7y)
//        Displacement(-6y,3y)
//        Displacement(-8y,2y)
//        Displacement(-6y,0y)
//        Displacement(-7y,-2y)
//        Displacement(-7y,-6y)
//        Displacement(-5y,-9y)
//        Displacement(-3y,-14y)
//        Displacement(0y,-19y)
//        Displacement(3y,-14y)
//        Displacement(5y,-10y)
//        Displacement(7y,-6y)
//        Displacement(7y,-3y)
//        Displacement(8y,0y)
//        Displacement(7y,1y)
//        Displacement(6y,4y)
//        Displacement(6y,6y)
//        Displacement(3y,9y)
//        PenUp
//        Displacement(-30y,63y)
//        PenDown
//        Displacement(-7y,-4y)
//        Displacement(-4y,-5y)
//        Displacement(-4y,-8y)
//        Displacement(-3y,-14y)
//        Displacement(0y,-19y)
//        Displacement(2y,-14y)
//        Displacement(4y,-10y)
//        Displacement(5y,-5y)
//        Displacement(7y,-4y)
//    ]
//    // ￡
//    dict.[41450us] <- [
//        PenUp
//        Displacement(20y,65y)
//        PenDown
//        Displacement(62y,0y)
//        PenUp
//        Displacement(-23y,43y)
//        PenDown
//        Displacement(-7y,-8y)
//        Displacement(-4y,-8y)
//        Displacement(-1y,-14y)
//        Displacement(0y,-45y)
//        Displacement(15y,-8y)
//        Displacement(7y,-3y)
//        Displacement(7y,0y)
//        Displacement(8y,3y)
//        Displacement(6y,4y)
//        Displacement(5y,4y)
//        PenUp
//        Displacement(-52y,-5y)
//        PenDown
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-4y,3y)
//        Displacement(-4y,1y)
//        Displacement(-5y,0y)
//        Displacement(-4y,-2y)
//        Displacement(-2y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        Displacement(0y,-3y)
//        Displacement(1y,-4y)
//        Displacement(2y,-4y)
//        Displacement(3y,-2y)
//        Displacement(3y,-1y)
//        Displacement(5y,0y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(3y,4y)
//        Displacement(1y,4y)
//        Displacement(0y,3y)
//        PenUp
//        Displacement(56y,16y)
//        PenDown
//        Displacement(-4y,-11y)
//        Displacement(-5y,-7y)
//        Displacement(-6y,-5y)
//        Displacement(-8y,-3y)
//        Displacement(-7y,0y)
//        Displacement(-7y,3y)
//        Displacement(-15y,8y)
//        Displacement(-1y,-6y)
//        Displacement(-2y,-5y)
//        Displacement(-3y,-4y)
//        Displacement(-4y,-3y)
//        Displacement(-6y,-1y)
//        Displacement(-4y,0y)
//        Displacement(-6y,2y)
//        Displacement(-3y,3y)
//        Displacement(-2y,4y)
//        Displacement(-1y,5y)
//        Displacement(0y,4y)
//        Displacement(1y,5y)
//        Displacement(2y,4y)
//        Displacement(4y,3y)
//        Displacement(4y,2y)
//        Displacement(6y,0y)
//        Displacement(6y,-2y)
//        Displacement(5y,-4y)
//        Displacement(0y,42y)
//        Displacement(2y,14y)
//        Displacement(5y,8y)
//        Displacement(9y,8y)
//        Displacement(8y,4y)
//        Displacement(10y,0y)
//        Displacement(8y,-4y)
//        Displacement(3y,-3y)
//        Displacement(2y,-7y)
//        Displacement(-4y,3y)
//        Displacement(-4y,-3y)
//        Displacement(0y,-4y)
//        Displacement(4y,-3y)
//        Displacement(4y,3y)
//        Displacement(0y,4y)
//    ]
//    // ‰
//    dict.[41451us] <- [
//        PenUp
//        Displacement(41y,110y)
//        PenDown
//        Displacement(-3y,2y)
//        Displacement(-5y,0y)
//        Displacement(-5y,-2y)
//        Displacement(-6y,-5y)
//        Displacement(-5y,-6y)
//        Displacement(-6y,-12y)
//        Displacement(-2y,-9y)
//        Displacement(0y,-7y)
//        Displacement(1y,-5y)
//        Displacement(3y,-3y)
//        Displacement(4y,0y)
//        Displacement(6y,1y)
//        Displacement(5y,3y)
//        Displacement(4y,4y)
//        Displacement(6y,8y)
//        Displacement(4y,10y)
//        Displacement(1y,7y)
//        Displacement(0y,7y)
//        Displacement(-1y,5y)
//        Displacement(-1y,2y)
//        PenUp
//        Displacement(34y,-50y)
//        PenDown
//        Displacement(-3y,2y)
//        Displacement(-5y,0y)
//        Displacement(-5y,-2y)
//        Displacement(-6y,-5y)
//        Displacement(-5y,-6y)
//        Displacement(-6y,-12y)
//        Displacement(-2y,-9y)
//        Displacement(0y,-7y)
//        Displacement(1y,-5y)
//        Displacement(3y,-3y)
//        Displacement(4y,0y)
//        Displacement(6y,1y)
//        Displacement(5y,3y)
//        Displacement(4y,4y)
//        Displacement(6y,8y)
//        Displacement(4y,10y)
//        Displacement(1y,7y)
//        Displacement(0y,7y)
//        Displacement(-1y,5y)
//        Displacement(-1y,2y)
//        PenUp
//        Displacement(40y,0y)
//        PenDown
//        Displacement(-3y,2y)
//        Displacement(-5y,0y)
//        Displacement(-5y,-2y)
//        Displacement(-6y,-5y)
//        Displacement(-5y,-6y)
//        Displacement(-6y,-12y)
//        Displacement(-2y,-9y)
//        Displacement(0y,-7y)
//        Displacement(1y,-5y)
//        Displacement(3y,-3y)
//        Displacement(4y,0y)
//        Displacement(6y,1y)
//        Displacement(5y,3y)
//        Displacement(4y,4y)
//        Displacement(6y,8y)
//        Displacement(4y,10y)
//        Displacement(1y,7y)
//        Displacement(0y,7y)
//        Displacement(-1y,5y)
//        Displacement(-1y,2y)
//        PenUp
//        Displacement(-39y,60y)
//        PenDown
//        Displacement(-66y,-111y)
//    ]
//    // §
//    dict.[41452us] <- [
//        PenUp
//        Displacement(73y,19y)
//        PenDown
//        Displacement(3y,-1y)
//        Displacement(3y,1y)
//        Displacement(1y,3y)
//        Displacement(-1y,3y)
//        Displacement(-3y,1y)
//        Displacement(-3y,-1y)
//        Displacement(-1y,-3y)
//        Displacement(2y,-7y)
//        Displacement(3y,-4y)
//        Displacement(6y,-3y)
//        Displacement(7y,-1y)
//        Displacement(7y,1y)
//        Displacement(7y,4y)
//        Displacement(2y,6y)
//        Displacement(0y,5y)
//        Displacement(-1y,4y)
//        Displacement(-5y,6y)
//        Displacement(-29y,26y)
//        Displacement(-3y,6y)
//        Displacement(-1y,5y)
//        Displacement(0y,2y)
//        Displacement(2y,4y)
//        Displacement(4y,4y)
//        Displacement(6y,2y)
//        Displacement(4y,0y)
//        Displacement(6y,-1y)
//        Displacement(4y,-2y)
//        PenUp
//        Displacement(9y,30y)
//        PenDown
//        Displacement(-3y,1y)
//        Displacement(-3y,-1y)
//        Displacement(-1y,-3y)
//        Displacement(1y,-3y)
//        Displacement(3y,-1y)
//        Displacement(3y,1y)
//        Displacement(1y,3y)
//        Displacement(-2y,7y)
//        Displacement(-3y,4y)
//        Displacement(-6y,3y)
//        Displacement(-7y,1y)
//        Displacement(-7y,-1y)
//        Displacement(-7y,-4y)
//        Displacement(-2y,-6y)
//        Displacement(0y,-5y)
//        Displacement(1y,-4y)
//        Displacement(5y,-6y)
//        Displacement(29y,-26y)
//        Displacement(3y,-6y)
//        Displacement(1y,-5y)
//        Displacement(0y,-2y)
//        Displacement(-2y,-4y)
//        Displacement(-4y,-4y)
//        Displacement(-6y,-2y)
//        Displacement(-4y,0y)
//        Displacement(-6y,1y)
//        Displacement(-4y,2y)
//    ]
//    // №
//    dict.[41453us] <- [
//        PenUp
//        Displacement(90y,88y)
//        PenDown
//        Displacement(5y,-2y)
//        Displacement(4y,-4y)
//        Displacement(2y,-6y)
//        Displacement(1y,-9y)
//        Displacement(0y,-35y)
//        Displacement(-1y,-9y)
//        Displacement(-2y,-6y)
//        Displacement(-4y,-4y)
//        Displacement(-5y,-2y)
//        Displacement(-6y,0y)
//        Displacement(-5y,2y)
//        Displacement(-4y,4y)
//        Displacement(-2y,6y)
//        Displacement(-1y,9y)
//        Displacement(0y,35y)
//        Displacement(1y,9y)
//        Displacement(2y,6y)
//        Displacement(4y,4y)
//        Displacement(5y,2y)
//        Displacement(6y,0y)
//        PenUp
//        Displacement(-87y,28y)
//        PenDown
//        Displacement(16y,0y)
//        Displacement(39y,-95y)
//        PenUp
//        Displacement(-44y,-10y)
//        PenDown
//        Displacement(0y,105y)
//        Displacement(44y,-105y)
//        Displacement(0y,105y)
//        PenUp
//        Displacement(-53y,-105y)
//        PenDown
//        Displacement(20y,0y)
//        PenUp
//        Displacement(45y,105y)
//        PenDown
//        Displacement(-24y,0y)
//        PenUp
//        Displacement(78y,-100y)
//        PenDown
//        Displacement(-1y,3y)
//        Displacement(-4y,2y)
//        Displacement(-4y,-2y)
//        Displacement(-1y,-3y)
//        Displacement(1y,-3y)
//        Displacement(4y,-2y)
//        Displacement(4y,2y)
//        Displacement(1y,3y)
//    ]
//    // ☆
//    dict.[41454us] <- [
//        PenUp
//        Displacement(64y,110y)
//        PenDown
//        Displacement(-14y,-34y)
//        Displacement(-34y,0y)
//        Displacement(26y,-20y)
//        Displacement(-10y,-34y)
//        Displacement(32y,19y)
//        Displacement(32y,-19y)
//        Displacement(-10y,34y)
//        Displacement(26y,20y)
//        Displacement(-34y,0y)
//        Displacement(-14y,34y)
//    ]
//    // ★
//    dict.[41455us] <- [
//        PenUp
//        Displacement(64y,110y)
//        PenDown
//        Displacement(-14y,-34y)
//        Displacement(-34y,0y)
//        Displacement(26y,-20y)
//        Displacement(-10y,-34y)
//        Displacement(32y,19y)
//        Displacement(32y,-19y)
//        Displacement(-10y,34y)
//        Displacement(26y,20y)
//        Displacement(-34y,0y)
//        Displacement(-14y,34y)
//        PenUp
//        Displacement(0y,-1y)
//        PenDown
//        Displacement(0y,-68y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,61y)
//        PenUp
//        Displacement(4y,-10y)
//        PenDown
//        Displacement(0y,-53y)
//        PenUp
//        Displacement(4y,-3y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,-4y)
//        PenDown
//        Displacement(0y,-44y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,-49y)
//        PenDown
//        Displacement(0y,21y)
//        PenUp
//        Displacement(0y,10y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,-15y)
//        PenUp
//        Displacement(0y,-26y)
//        PenDown
//        Displacement(0y,-10y)
//        PenUp
//        Displacement(4y,51y)
//        PenDown
//        Displacement(0y,-12y)
//        PenUp
//        Displacement(4y,12y)
//        PenDown
//        Displacement(0y,-9y)
//        PenUp
//        Displacement(4y,3y)
//        PenDown
//        Displacement(0y,6y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,-3y)
//        PenUp
//        Displacement(-88y,3y)
//        PenDown
//        Displacement(0y,-3y)
//        PenUp
//        Displacement(4y,-3y)
//        PenDown
//        Displacement(0y,6y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,-9y)
//        PenUp
//        Displacement(4y,9y)
//        PenDown
//        Displacement(0y,-12y)
//        PenUp
//        Displacement(4y,-29y)
//        PenDown
//        Displacement(0y,-10y)
//        PenUp
//        Displacement(0y,51y)
//        PenDown
//        Displacement(0y,-15y)
//        PenUp
//        Displacement(4y,-3y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(0y,-49y)
//        PenDown
//        Displacement(0y,21y)
//        PenUp
//        Displacement(4y,-18y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,-44y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,10y)
//        PenDown
//        Displacement(0y,-53y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,61y)
//    ]
//    // ○
//    dict.[41456us] <- [
//        PenUp
//        Displacement(118y,64y)
//        PenDown
//        Displacement(-1y,11y)
//        Displacement(-3y,10y)
//        Displacement(-5y,9y)
//        Displacement(-7y,8y)
//        Displacement(-8y,7y)
//        Displacement(-9y,5y)
//        Displacement(-10y,3y)
//        Displacement(-11y,1y)
//        Displacement(-11y,-1y)
//        Displacement(-10y,-3y)
//        Displacement(-9y,-5y)
//        Displacement(-8y,-7y)
//        Displacement(-7y,-8y)
//        Displacement(-5y,-9y)
//        Displacement(-3y,-10y)
//        Displacement(-1y,-11y)
//        Displacement(1y,-11y)
//        Displacement(3y,-10y)
//        Displacement(5y,-9y)
//        Displacement(7y,-8y)
//        Displacement(8y,-7y)
//        Displacement(9y,-5y)
//        Displacement(10y,-3y)
//        Displacement(11y,-1y)
//        Displacement(11y,1y)
//        Displacement(10y,3y)
//        Displacement(9y,5y)
//        Displacement(8y,7y)
//        Displacement(7y,8y)
//        Displacement(5y,9y)
//        Displacement(3y,10y)
//        Displacement(1y,11y)
//    ]
//    // ●
//    dict.[41457us] <- [
//        PenUp
//        Displacement(104y,64y)
//        PenDown
//        Displacement(-1y,10y)
//        Displacement(-4y,10y)
//        Displacement(-7y,9y)
//        Displacement(-8y,6y)
//        Displacement(-10y,4y)
//        Displacement(-10y,1y)
//        Displacement(-10y,-1y)
//        Displacement(-10y,-4y)
//        Displacement(-8y,-6y)
//        Displacement(-7y,-9y)
//        Displacement(-4y,-10y)
//        Displacement(-1y,-10y)
//        Displacement(1y,-10y)
//        Displacement(4y,-10y)
//        Displacement(7y,-9y)
//        Displacement(8y,-6y)
//        Displacement(10y,-4y)
//        Displacement(10y,-1y)
//        Displacement(10y,1y)
//        Displacement(10y,4y)
//        Displacement(8y,6y)
//        Displacement(7y,9y)
//        Displacement(4y,10y)
//        Displacement(1y,10y)
//        PenUp
//        Displacement(0y,0y)
//        PenDown
//        Displacement(-80y,0y)
//        PenUp
//        Displacement(1y,-4y)
//        PenDown
//        Displacement(78y,0y)
//        PenUp
//        Displacement(-1y,-4y)
//        PenDown
//        Displacement(-76y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(76y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(-72y,0y)
//        PenUp
//        Displacement(2y,-4y)
//        PenDown
//        Displacement(68y,0y)
//        PenUp
//        Displacement(-3y,-4y)
//        PenDown
//        Displacement(-62y,0y)
//        PenUp
//        Displacement(3y,-4y)
//        PenDown
//        Displacement(56y,0y)
//        PenUp
//        Displacement(-5y,-4y)
//        PenDown
//        Displacement(-46y,0y)
//        PenUp
//        Displacement(7y,-4y)
//        PenDown
//        Displacement(32y,0y)
//        PenUp
//        Displacement(-32y,72y)
//        PenDown
//        Displacement(32y,0y)
//        PenUp
//        Displacement(7y,-4y)
//        PenDown
//        Displacement(-46y,0y)
//        PenUp
//        Displacement(-5y,-4y)
//        PenDown
//        Displacement(56y,0y)
//        PenUp
//        Displacement(3y,-4y)
//        PenDown
//        Displacement(-62y,0y)
//        PenUp
//        Displacement(-3y,-4y)
//        PenDown
//        Displacement(68y,0y)
//        PenUp
//        Displacement(2y,-4y)
//        PenDown
//        Displacement(-72y,0y)
//        PenUp
//        Displacement(-2y,-4y)
//        PenDown
//        Displacement(76y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(-76y,0y)
//        PenUp
//        Displacement(-1y,-4y)
//        PenDown
//        Displacement(78y,0y)
//    ]
//    // ◎
//    dict.[41458us] <- [
//        PenUp
//        Displacement(118y,64y)
//        PenDown
//        Displacement(-1y,11y)
//        Displacement(-3y,10y)
//        Displacement(-5y,9y)
//        Displacement(-7y,8y)
//        Displacement(-8y,7y)
//        Displacement(-9y,5y)
//        Displacement(-10y,3y)
//        Displacement(-11y,1y)
//        Displacement(-11y,-1y)
//        Displacement(-10y,-3y)
//        Displacement(-9y,-5y)
//        Displacement(-8y,-7y)
//        Displacement(-7y,-8y)
//        Displacement(-5y,-9y)
//        Displacement(-3y,-10y)
//        Displacement(-1y,-11y)
//        Displacement(1y,-11y)
//        Displacement(3y,-10y)
//        Displacement(5y,-9y)
//        Displacement(7y,-8y)
//        Displacement(8y,-7y)
//        Displacement(9y,-5y)
//        Displacement(10y,-3y)
//        Displacement(11y,-1y)
//        Displacement(11y,1y)
//        Displacement(10y,3y)
//        Displacement(9y,5y)
//        Displacement(8y,7y)
//        Displacement(7y,8y)
//        Displacement(5y,9y)
//        Displacement(3y,10y)
//        Displacement(1y,11y)
//        PenUp
//        Displacement(-18y,0y)
//        PenDown
//        Displacement(-1y,8y)
//        Displacement(-3y,8y)
//        Displacement(-4y,7y)
//        Displacement(-5y,5y)
//        Displacement(-7y,4y)
//        Displacement(-8y,3y)
//        Displacement(-8y,1y)
//        Displacement(-8y,-1y)
//        Displacement(-8y,-3y)
//        Displacement(-7y,-4y)
//        Displacement(-5y,-5y)
//        Displacement(-4y,-7y)
//        Displacement(-3y,-8y)
//        Displacement(-1y,-8y)
//        Displacement(1y,-8y)
//        Displacement(3y,-8y)
//        Displacement(4y,-7y)
//        Displacement(5y,-5y)
//        Displacement(7y,-4y)
//        Displacement(8y,-3y)
//        Displacement(8y,-1y)
//        Displacement(8y,1y)
//        Displacement(8y,3y)
//        Displacement(7y,4y)
//        Displacement(5y,5y)
//        Displacement(4y,7y)
//        Displacement(3y,8y)
//        Displacement(1y,8y)
//    ]
//    // ◇
//    dict.[41459us] <- [
//        PenUp
//        Displacement(8y,64y)
//        PenDown
//        Displacement(56y,56y)
//        Displacement(56y,-56y)
//        Displacement(-56y,-56y)
//        Displacement(-56y,56y)
//    ]
//    // ◆
//    dict.[41460us] <- [
//        PenUp
//        Displacement(8y,64y)
//        PenDown
//        Displacement(56y,56y)
//        Displacement(56y,-56y)
//        Displacement(-56y,-56y)
//        Displacement(-56y,56y)
//        PenUp
//        Displacement(56y,-56y)
//        PenDown
//        Displacement(0y,112y)
//        PenUp
//        Displacement(4y,-4y)
//        PenDown
//        Displacement(0y,-104y)
//        PenUp
//        Displacement(4y,100y)
//        PenDown
//        Displacement(0y,-96y)
//        PenUp
//        Displacement(4y,92y)
//        PenDown
//        Displacement(0y,-88y)
//        PenUp
//        Displacement(4y,84y)
//        PenDown
//        Displacement(0y,-80y)
//        PenUp
//        Displacement(4y,76y)
//        PenDown
//        Displacement(0y,-72y)
//        PenUp
//        Displacement(4y,68y)
//        PenDown
//        Displacement(0y,-64y)
//        PenUp
//        Displacement(4y,60y)
//        PenDown
//        Displacement(0y,-56y)
//        PenUp
//        Displacement(4y,52y)
//        PenDown
//        Displacement(0y,-48y)
//        PenUp
//        Displacement(4y,44y)
//        PenDown
//        Displacement(0y,-40y)
//        PenUp
//        Displacement(4y,36y)
//        PenDown
//        Displacement(0y,-32y)
//        PenUp
//        Displacement(4y,28y)
//        PenDown
//        Displacement(0y,-24y)
//        PenUp
//        Displacement(4y,20y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(4y,12y)
//        PenDown
//        Displacement(0y,-8y)
//        PenUp
//        Displacement(-104y,8y)
//        PenDown
//        Displacement(0y,-8y)
//        PenUp
//        Displacement(4y,12y)
//        PenDown
//        Displacement(0y,-16y)
//        PenUp
//        Displacement(4y,20y)
//        PenDown
//        Displacement(0y,-24y)
//        PenUp
//        Displacement(4y,28y)
//        PenDown
//        Displacement(0y,-32y)
//        PenUp
//        Displacement(4y,36y)
//        PenDown
//        Displacement(0y,-40y)
//        PenUp
//        Displacement(4y,44y)
//        PenDown
//        Displacement(0y,-48y)
//        PenUp
//        Displacement(4y,52y)
//        PenDown
//        Displacement(0y,-56y)
//        PenUp
//        Displacement(4y,60y)
//        PenDown
//        Displacement(0y,-64y)
//        PenUp
//        Displacement(4y,68y)
//        PenDown
//        Displacement(0y,-72y)
//        PenUp
//        Displacement(4y,76y)
//        PenDown
//        Displacement(0y,-80y)
//        PenUp
//        Displacement(4y,84y)
//        PenDown
//        Displacement(0y,-88y)
//        PenUp
//        Displacement(4y,92y)
//        PenDown
//        Displacement(0y,-96y)
//        PenUp
//        Displacement(4y,100y)
//        PenDown
//        Displacement(0y,-104y)
//    ]
//    // □
//    dict.[41461us] <- [
//        PenUp
//        Displacement(11y,115y)
//        PenDown
//        Displacement(104y,0y)
//        Displacement(0y,-104y)
//        Displacement(-104y,0y)
//        Displacement(0y,104y)
//    ]
//    // ■
//    dict.[41462us] <- [
//        PenUp
//        Displacement(12y,117y)
//        PenDown
//        Displacement(104y,0y)
//        Displacement(0y,-104y)
//        Displacement(-104y,0y)
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//        PenUp
//        Displacement(4y,-104y)
//        PenDown
//        Displacement(0y,104y)
//    ]
//    // △
//    dict.[41463us] <- [
//        PenUp
//        Displacement(14y,18y)
//        PenDown
//        Displacement(100y,0y)
//        Displacement(-50y,91y)
//        Displacement(-50y,-91y)
//    ]
//    // ▲
//    dict.[41464us] <- [
//        PenUp
//        Displacement(14y,18y)
//        PenDown
//        Displacement(100y,0y)
//        Displacement(-50y,91y)
//        Displacement(-50y,-91y)
//        PenUp
//        Displacement(50y,0y)
//        PenDown
//        Displacement(0y,91y)
//        PenUp
//        Displacement(4y,-91y)
//        PenDown
//        Displacement(0y,83y)
//        PenUp
//        Displacement(4y,-83y)
//        PenDown
//        Displacement(0y,75y)
//        PenUp
//        Displacement(4y,-75y)
//        PenDown
//        Displacement(0y,68y)
//        PenUp
//        Displacement(4y,-68y)
//        PenDown
//        Displacement(0y,61y)
//        PenUp
//        Displacement(4y,-61y)
//        PenDown
//        Displacement(0y,54y)
//        PenUp
//        Displacement(4y,-54y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,-46y)
//        PenDown
//        Displacement(0y,39y)
//        PenUp
//        Displacement(4y,-39y)
//        PenDown
//        Displacement(0y,32y)
//        PenUp
//        Displacement(4y,-32y)
//        PenDown
//        Displacement(0y,24y)
//        PenUp
//        Displacement(4y,-24y)
//        PenDown
//        Displacement(0y,17y)
//        PenUp
//        Displacement(4y,-17y)
//        PenDown
//        Displacement(0y,10y)
//        PenUp
//        Displacement(4y,-10y)
//        PenDown
//        Displacement(0y,3y)
//        PenUp
//        Displacement(-96y,-3y)
//        PenDown
//        Displacement(0y,3y)
//        PenUp
//        Displacement(4y,-3y)
//        PenDown
//        Displacement(0y,10y)
//        PenUp
//        Displacement(4y,-10y)
//        PenDown
//        Displacement(0y,17y)
//        PenUp
//        Displacement(4y,-17y)
//        PenDown
//        Displacement(0y,24y)
//        PenUp
//        Displacement(4y,-24y)
//        PenDown
//        Displacement(0y,32y)
//        PenUp
//        Displacement(4y,-32y)
//        PenDown
//        Displacement(0y,39y)
//        PenUp
//        Displacement(4y,-39y)
//        PenDown
//        Displacement(0y,46y)
//        PenUp
//        Displacement(4y,-46y)
//        PenDown
//        Displacement(0y,54y)
//        PenUp
//        Displacement(4y,-54y)
//        PenDown
//        Displacement(0y,61y)
//        PenUp
//        Displacement(4y,-61y)
//        PenDown
//        Displacement(0y,68y)
//        PenUp
//        Displacement(4y,-68y)
//        PenDown
//        Displacement(0y,75y)
//        PenUp
//        Displacement(4y,-75y)
//        PenDown
//        Displacement(0y,83y)
//    ]
//    // ※
//    dict.[41465us] <- [
//        PenUp
//        Displacement(54y,32y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(-35y,32y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(35y,35y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(31y,-35y)
//        PenDown
//        Displacement(1y,-4y)
//        Displacement(2y,-3y)
//        Displacement(3y,-2y)
//        Displacement(4y,-1y)
//        Displacement(4y,1y)
//        Displacement(3y,2y)
//        Displacement(2y,3y)
//        Displacement(1y,4y)
//        Displacement(-1y,4y)
//        Displacement(-2y,3y)
//        Displacement(-3y,2y)
//        Displacement(-4y,1y)
//        Displacement(-4y,-1y)
//        Displacement(-3y,-2y)
//        Displacement(-2y,-3y)
//        Displacement(-1y,-4y)
//        PenUp
//        Displacement(28y,49y)
//        PenDown
//        Displacement(-100y,-100y)
//        PenUp
//        Displacement(2y,100y)
//        PenDown
//        Displacement(100y,-100y)
//        PenUp
//        Displacement(-92y,44y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(4y,2y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(4y,0y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(4y,-2y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(66y,14y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(-19y,35y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//        PenUp
//        Displacement(12y,-67y)
//        PenDown
//        Displacement(0y,-14y)
//        PenUp
//        Displacement(-4y,-2y)
//        PenDown
//        Displacement(0y,18y)
//        PenUp
//        Displacement(-4y,0y)
//        PenDown
//        Displacement(0y,-18y)
//        PenUp
//        Displacement(-4y,2y)
//        PenDown
//        Displacement(0y,14y)
//    ]
//    // →
//    dict.[41466us] <- [
//        PenUp
//        Displacement(5y,64y)
//        PenDown
//        Displacement(118y,0y)
//        Displacement(-51y,17y)
//        Displacement(11y,-17y)
//        Displacement(-11y,-17y)
//        Displacement(51y,17y)
//    ]
//    // ←
//    dict.[41467us] <- [
//        PenUp
//        Displacement(121y,64y)
//        PenDown
//        Displacement(-118y,0y)
//        Displacement(51y,17y)
//        Displacement(-11y,-17y)
//        Displacement(11y,-17y)
//        Displacement(-51y,17y)
//    ]
//    // ↑
//    dict.[41468us] <- [
//        PenUp
//        Displacement(64y,6y)
//        PenDown
//        Displacement(0y,118y)
//        Displacement(17y,-51y)
//        Displacement(-17y,11y)
//        Displacement(-17y,-11y)
//        Displacement(17y,51y)
//    ]
//    // ↓
//    dict.[41469us] <- [
//        PenUp
//        Displacement(64y,123y)
//        PenDown
//        Displacement(0y,-118y)
//        Displacement(-17y,51y)
//        Displacement(17y,-11y)
//        Displacement(17y,11y)
//        Displacement(-17y,-51y)
//    ]
//    // 〓
//    dict.[41470us] <- [
//        PenUp
//        Displacement(15y,40y)
//        PenDown
//        Displacement(98y,0y)
//        Displacement(0y,-20y)
//        Displacement(-98y,0y)
//        Displacement(0y,20y)
//        PenUp
//        Displacement(0y,58y)
//        PenDown
//        Displacement(98y,0y)
//        Displacement(0y,-20y)
//        Displacement(-98y,0y)
//        Displacement(0y,20y)
//        PenUp
//        Displacement(0y,-74y)
//        PenDown
//        Displacement(98y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-98y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(98y,0y)
//        PenUp
//        Displacement(0y,4y)
//        PenDown
//        Displacement(-98y,0y)
//        PenUp
//        Displacement(98y,58y)
//        PenDown
//        Displacement(-98y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(98y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(-98y,0y)
//        PenUp
//        Displacement(0y,-4y)
//        PenDown
//        Displacement(98y,0y)
//    ]
//    Map.fromInterface dict
